name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you'd like to see!
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What other approaches might work?
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: What type of feature is this?
      description: Help us categorize your request
      options:
        - New functionality
        - Improvement to existing feature
        - Performance enhancement
        - UI/UX improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: This helps us prioritize development
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Example: As a data analyst, I want to export data in CSV format so that I can easily import it into my analysis tools.
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how this could be implemented, please share them
      placeholder: Any thoughts on how this could work technically?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Is there anything else that would help us understand this request?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our community guidelines.
      options:
        - label: I have read and agree to the community guidelines
          required: true 